export const salesListMockData = [
  {
    OrderId: 'fi3sd',
    fixed: false,
    ProductName: 'Gaming Laptop XYZ',
    QuantitySold: 10,
    QuantityOrders: 12,
    TotalPrice: 12000,
    Region: 'North America',
  },
  {
    OrderId: 't8hgf',
    fixed: false,
    ProductName: 'Wireless Mouse ABC',
    QuantitySold: 50,
    QuantityOrders: 51,
    TotalPrice: 1500,
    Region: 'Europe',
  },
  {
    OrderId: 'y6kdf',
    fixed: false,
    ProductName: 'Mechanical Keyboard QWERTY',
    QuantitySold: 30,
    QuantityOrders: 31,
    TotalPrice: 3000,
    Region: 'Asia',
  },
  {
    OrderId: 'z2rhk',
    fixed: false,
    ProductName: 'External SSD 1TB',
    QuantitySold: 20,
    QuantityOrders: 22,
    TotalPrice: 4000,
    Region: 'Australia',
  },
  {
    OrderId: 'j3yhb',
    fixed: false,
    ProductName: 'Gaming Monitor 27 inches',
    QuantitySold: 15,
    QuantityOrders: 17,
    TotalPrice: 4500,
    Region: 'South America',
  },
  {
    OrderId: 'g8xvb',
    fixed: false,
    ProductName: 'Laptop Stand Ergonomic',
    QuantitySold: 25,
    QuantityOrders: 28,
    TotalPrice: 1250,
    Region: 'Africa',
  },
  {
    OrderId: 'w2vju',
    fixed: false,
    ProductName: 'USB-C Hub Multiport',
    QuantitySold: 40,
    QuantityOrders: 45,
    TotalPrice: 2000,
    Region: 'North America',
  },
  {
    OrderId: 'n5dqe',
    fixed: false,
    ProductName: 'Laptop Backpack',
    QuantitySold: 35,
    QuantityOrders: 41,
    TotalPrice: 1750,
    Region: 'Europe',
  },
  {
    OrderId: 'b9ctf',
    fixed: false,
    ProductName: 'Portable Laptop Charger',
    QuantitySold: 22,
    QuantityOrders: 22,
    TotalPrice: 1100,
    Region: 'Asia',
  },
  {
    OrderId: 'u3hsl',
    fixed: false,
    ProductName: 'Gaming Headset',
    QuantitySold: 12,
    QuantityOrders: 16,
    TotalPrice: 2400,
    Region: 'Australia',
  },
  {
    OrderId: 'p4mzt',
    fixed: false,
    ProductName: 'Wireless Earbuds',
    QuantitySold: 18,
    QuantityOrders: 21,
    TotalPrice: 1800,
    Region: 'North America',
  },
  {
    OrderId: 'r7jxc',
    fixed: false,
    ProductName: 'Mechanical Gaming Keyboard',
    QuantitySold: 11,
    QuantityOrders: 12,
    TotalPrice: 2200,
    Region: 'Europe',
  },
  {
    OrderId: 'a1dko',
    fixed: false,
    ProductName: 'HDMI Cable 2M',
    QuantitySold: 45,
    QuantityOrders: 55,
    TotalPrice: 450,
    Region: 'Asia',
  },
  {
    OrderId: 'v5jrh',
    fixed: false,
    ProductName: 'Webcam HD 1080p',
    QuantitySold: 27,
    QuantityOrders: 32,
    TotalPrice: 1350,
    Region: 'Australia',
  },
  {
    OrderId: 'c2zfg',
    fixed: false,
    ProductName: 'Portable Bluetooth Speaker',
    QuantitySold: 20,
    QuantityOrders: 24,
    TotalPrice: 2000,
    Region: 'South America',
  },
  {
    OrderId: 'e6msh',
    fixed: false,
    ProductName: 'Laptop Cooling Pad',
    QuantitySold: 15,
    QuantityOrders: 19,
    TotalPrice: 750,
    Region: 'Africa',
  },
  {
    OrderId: 'j9dqe',
    fixed: false,
    ProductName: 'USB Flash Drive 64GB',
    QuantitySold: 40,
    QuantityOrders: 40,
    TotalPrice: 800,
    Region: 'North America',
  },
  {
    OrderId: 'q5klh',
    fixed: false,
    ProductName: 'Laptop Sleeve 15 inch',
    QuantitySold: 30,
    QuantityOrders: 30,
    TotalPrice: 600,
    Region: 'Europe',
  },
  {
    OrderId: 'z2vtx',
    fixed: false,
    ProductName: 'Graphic Card XYZ',
    QuantitySold: 5,
    QuantityOrders: 5,
    TotalPrice: 15000,
    Region: 'Asia',
  },
  {
    OrderId: 'g3jvd',
    fixed: false,
    ProductName: 'Gaming Chair',
    QuantitySold: 10,
    QuantityOrders: 10,
    TotalPrice: 5000,
    Region: 'Australia',
  },
  {
    OrderId: 'p1tjk',
    fixed: false,
    ProductName: 'External Hard Drive 2TB',
    QuantitySold: 8,
    QuantityOrders: 8,
    TotalPrice: 1600,
    Region: 'South America',
  },
  {
    OrderId: 'x4lfg',
    fixed: false,
    ProductName: 'VR Headset',
    QuantitySold: 6,
    QuantityOrders: 6,
    TotalPrice: 3000,
    Region: 'Africa',
  },
  {
    OrderId: 't8rvc',
    fixed: false,
    ProductName: 'Computer Desk',
    QuantitySold: 7,
    QuantityOrders: 7,
    TotalPrice: 2100,
    Region: 'North America',
  },
  {
    OrderId: 'a3vsh',
    fixed: false,
    ProductName: 'Laptop Stand Adjustable',
    QuantitySold: 20,
    QuantityOrders: 21,
    TotalPrice: 1000,
    Region: 'Europe',
  },
  {
    OrderId: 'c4dqe',
    fixed: false,
    ProductName: 'Mouse Pad XXL',
    QuantitySold: 35,
    QuantityOrders: 37,
    TotalPrice: 1050,
    Region: 'Asia',
  },
  {
    OrderId: 'e5mxd',
    fixed: false,
    ProductName: 'HDMI Splitter',
    QuantitySold: 25,
    QuantityOrders: 29,
    TotalPrice: 1250,
    Region: 'Australia',
  },
  {
    OrderId: 'n8kzh',
    fixed: false,
    ProductName: 'Laptop with i7 Processor',
    QuantitySold: 9,
    QuantityOrders: 9,
    TotalPrice: 9000,
    Region: 'South America',
  },
  {
    OrderId: 'v1pje',
    fixed: false,
    ProductName: 'Bluetooth Keyboard',
    QuantitySold: 12,
    QuantityOrders: 12,
    TotalPrice: 1200,
    Region: 'Africa',
  },
  {
    OrderId: 'f7btk',
    fixed: false,
    ProductName: 'Noise-Canceling Headphones',
    QuantitySold: 15,
    QuantityOrders: 16,
    TotalPrice: 3000,
    Region: 'North America',
  },
  {
    OrderId: 'j2sfr',
    fixed: false,
    ProductName: 'LED Monitor 24 inches',
    QuantitySold: 10,
    QuantityOrders: 12,
    TotalPrice: 2000,
    Region: 'Europe',
  },
  {
    OrderId: 'z5jxk',
    fixed: false,
    ProductName: 'Computer Speaker Set',
    QuantitySold: 20,
    QuantityOrders: 22,
    TotalPrice: 2000,
    Region: 'Asia',
  },
  {
    OrderId: 'c8lrd',
    fixed: false,
    ProductName: 'Wi-Fi Range Extender',
    QuantitySold: 14,
    QuantityOrders: 15,
    TotalPrice: 1400,
    Region: 'Australia',
  },
  {
    OrderId: 'k1qbf',
    fixed: false,
    ProductName: 'Laptop with 16GB RAM',
    QuantitySold: 11,
    QuantityOrders: 13,
    TotalPrice: 11000,
    Region: 'South America',
  },
  {
    OrderId: 'g4vch',
    fixed: false,
    ProductName: 'Docking Station',
    QuantitySold: 8,
    QuantityOrders: 12,
    TotalPrice: 2400,
    Region: 'Africa',
  },
  {
    OrderId: 'd9bsp',
    fixed: false,
    ProductName: 'Microphone USB',
    QuantitySold: 17,
    QuantityOrders: 18,
    TotalPrice: 850,
    Region: 'North America',
  },
  {
    OrderId: 'j0tdk',
    fixed: false,
    ProductName: 'Graphics Drawing Tablet',
    QuantitySold: 6,
    QuantityOrders: 12,
    TotalPrice: 1200,
    Region: 'Europe',
  },
  {
    OrderId: 't2fzk',
    fixed: false,
    ProductName: 'Laptop with 1TB SSD',
    QuantitySold: 5,
    QuantityOrders: 12,
    TotalPrice: 13000,
    Region: 'Asia',
  },
  {
    OrderId: 'n5kqd',
    fixed: false,
    ProductName: 'Gaming Mouse Pad',
    QuantitySold: 15,
    QuantityOrders: 16,
    TotalPrice: 300,
    Region: 'Australia',
  },
  {
    OrderId: 'p7ljs',
    fixed: false,
    ProductName: '2-in-1 Laptop',
    QuantitySold: 7,
    QuantityOrders: 12,
    TotalPrice: 8000,
    Region: 'South America',
  },
  {
    OrderId: 'f9gqc',
    fixed: false,
    ProductName: 'Stylus Pen for Tablet',
    QuantitySold: 25,
    QuantityOrders: 26,
    TotalPrice: 1250,
    Region: 'Africa',
  },
  {
    OrderId: 'm8pvd',
    fixed: false,
    ProductName: 'LED Strip Lights for Gaming',
    QuantitySold: 10,
    QuantityOrders: 12,
    TotalPrice: 500,
    Region: 'North America',
  },
  {
    OrderId: 'd3gzh',
    fixed: false,
    ProductName: 'Laptop with Ryzen 5',
    QuantitySold: 9,
    QuantityOrders: 12,
    TotalPrice: 9000,
    Region: 'Europe',
  },
  {
    OrderId: 'k5sjd',
    fixed: false,
    ProductName: 'Portable Monitor 15.6 inches',
    QuantitySold: 14,
    QuantityOrders: 16,
    TotalPrice: 2800,
    Region: 'Asia',
  },
  {
    OrderId: 'h1aew',
    fixed: false,
    ProductName: 'Laptop with OLED Display',
    QuantitySold: 3,
    QuantityOrders: 12,
    TotalPrice: 15000,
    Region: 'Australia',
  },
  {
    OrderId: 'c2yld',
    fixed: false,
    ProductName: 'Wireless Gaming Mouse',
    QuantitySold: 22,
    QuantityOrders: 22,
    TotalPrice: 1100,
    Region: 'South America',
  },
  {
    OrderId: 'n9wfg',
    fixed: false,
    ProductName: 'HDMI to VGA Adapter',
    QuantitySold: 25,
    QuantityOrders: 32,
    TotalPrice: 500,
    Region: 'North America',
  },
  {
    OrderId: 'r6tkr',
    fixed: false,
    ProductName: 'Gaming Laptop ABC',
    QuantitySold: 10,
    QuantityOrders: 12,
    TotalPrice: 14000,
    Region: 'Europe',
  },
  {
    OrderId: 'f1eqp',
    fixed: false,
    ProductName: 'Wireless Charger',
    QuantitySold: 20,
    QuantityOrders: 22,
    TotalPrice: 2000,
    Region: 'Asia',
  },
  {
    OrderId: 'h5mnl',
    fixed: false,
    ProductName: 'Bluetooth Adapter',
    QuantitySold: 15,
    QuantityOrders: 22,
    TotalPrice: 750,
    Region: 'Australia',
  },
  {
    OrderId: 'l2jcb',
    fixed: false,
    ProductName: 'Gaming Monitor 32 inches',
    QuantitySold: 5,
    QuantityOrders: 12,
    TotalPrice: 3000,
    Region: 'South America',
  },
  {
    OrderId: 'e9vhd',
    fixed: false,
    ProductName: 'Computer Mouse RGB',
    QuantitySold: 30,
    QuantityOrders: 32,
    TotalPrice: 900,
    Region: 'Africa',
  },
  {
    OrderId: 'x4qla',
    fixed: false,
    ProductName: 'Laptop with 512GB SSD',
    QuantitySold: 12,
    QuantityOrders: 12,
    TotalPrice: 8500,
    Region: 'North America',
  },
  {
    OrderId: 'j3yzb',
    fixed: false,
    ProductName: 'Ergonomic Chair',
    QuantitySold: 8,
    QuantityOrders: 12,
    TotalPrice: 4000,
    Region: 'Europe',
  },
  {
    OrderId: 'd8hse',
    fixed: false,
    ProductName: 'Smartphone Holder',
    QuantitySold: 18,
    QuantityOrders: 22,
    TotalPrice: 360,
    Region: 'Asia',
  },
  {
    OrderId: 'f2udk',
    fixed: false,
    ProductName: 'USB Hub 3.0',
    QuantitySold: 25,
    QuantityOrders: 29,
    TotalPrice: 1250,
    Region: 'Australia',
  },
  {
    OrderId: 'q6pxt',
    fixed: false,
    ProductName: 'Laptop with 8GB RAM',
    QuantitySold: 20,
    QuantityOrders: 22,
    TotalPrice: 7000,
    Region: 'South America',
  },
  {
    OrderId: 'm4ywj',
    fixed: false,
    ProductName: 'Power Bank 20000mAh',
    QuantitySold: 30,
    QuantityOrders: 32,
    TotalPrice: 1200,
    Region: 'Africa',
  },
  {
    OrderId: 'l5jzf',
    fixed: false,
    ProductName: 'Wi-Fi Router',
    QuantitySold: 15,
    QuantityOrders: 15,
    TotalPrice: 3000,
    Region: 'North America',
  },
  {
    OrderId: 'e2vtm',
    fixed: false,
    ProductName: 'Laptop with HD Display',
    QuantitySold: 10,
    QuantityOrders: 12,
    TotalPrice: 6000,
    Region: 'Europe',
  },
  {
    OrderId: 'g3jhf',
    fixed: false,
    ProductName: 'Gaming Keyboard RGB',
    QuantitySold: 5,
    QuantityOrders: 12,
    TotalPrice: 2500,
    Region: 'Asia',
  },
  {
    OrderId: 'd7wnr',
    fixed: false,
    ProductName: 'Noise-Canceling Earbuds',
    QuantitySold: 25,
    QuantityOrders: 35,
    TotalPrice: 2500,
    Region: 'Australia',
  },
  {
    OrderId: 'v1cxe',
    fixed: false,
    ProductName: 'Laptop with Backlit Keyboard',
    QuantitySold: 10,
    QuantityOrders: 12,
    TotalPrice: 7000,
    Region: 'South America',
  },
  {
    OrderId: 'f9khz',
    fixed: false,
    ProductName: 'Computer Repair Kit',
    QuantitySold: 12,
    QuantityOrders: 12,
    TotalPrice: 600,
    Region: 'Africa',
  },
  {
    OrderId: 'm4pyt',
    fixed: false,
    ProductName: 'Smart Monitor',
    QuantitySold: 8,
    QuantityOrders: 12,
    TotalPrice: 5000,
    Region: 'North America',
  },
  {
    OrderId: 'l6qvn',
    fixed: false,
    ProductName: 'Laptop with 4GB RAM',
    QuantitySold: 15,
    QuantityOrders: 15,
    TotalPrice: 4000,
    Region: 'Europe',
  },
  {
    OrderId: 'k5wzb',
    fixed: false,
    ProductName: 'Laptop with 144Hz Display',
    QuantitySold: 7,
    QuantityOrders: 12,
    TotalPrice: 9000,
    Region: 'Asia',
  },
  {
    OrderId: 'd1xkc',
    fixed: false,
    ProductName: 'RGB Gaming Mouse',
    QuantitySold: 20,
    QuantityOrders: 20,
    TotalPrice: 2000,
    Region: 'Australia',
  },
  {
    OrderId: 'c9shx',
    fixed: false,
    ProductName: 'Laptop with Long Battery Life',
    QuantitySold: 10,
    QuantityOrders: 12,
    TotalPrice: 8000,
    Region: 'South America',
  },
  {
    OrderId: 'n4xjz',
    fixed: false,
    ProductName: 'USB-C to HDMI Adapter',
    QuantitySold: 35,
    QuantityOrders: 36,
    TotalPrice: 1750,
    Region: 'Africa',
  },
]

export const salesChartMockData = {
  datasets: [
    {
      data: [104, 111, 124, 88, 200, 233, 187, 181, 201, 224, 280, 240],
      label: 'Laptops',
      backgroundColor: '#EA906C',
      borderColor: '#EA906C',
    },
  ],
  labels: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],
}

export const salesCardsMockData = [
  {
    title: 'Total sales',
    text: '100',
  },
  {
    title: 'Number of orders',
    text: '132',
  },
  {
    title: 'Top-performing product',
    text: 'Apples',
  },
  {
    title: 'Sales growth percentage',
    text: '43%',
  },
]
